# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Kody Peterson'
tagline:             'Full Stack Web Application Developer'
description:         ''
url:                 http://www.kodypeterson.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Kody Peterson
  url:               https://twitter.com/kodypeterson
  email:             kodypeterson91@gmail.com

# Custom vars
version:             1.0.0
